server:
  port: 8080

spring:
  profiles:
    active: @application.profile@
  application:
    name: game
  redis:
    jedis:
      pool:
        max-active: -1
        max-idle: 20
        max-wait: 500ms
        min-idle: 8
    lettuce:
      pool:
        min-idle: 5
        max-idle: 20
        max-active: 50
    timeout: 60000ms
    database: 0
    host: @spring.redis.host@
    port: @spring.redis.port@
  servlet:
    multipart:
      max-request-size: 150MB
      max-file-size: 100MB
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: @spring.datasource.url@
    username: @spring.datasource.username@
    password: @spring.datasource.password@
    driver-class-name: @spring.datasource.driver-class-name@
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      remove-abandoned: true
      remove-abandoned-timeout: 180
      validation-query: select 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      stat-view-servlet:
        enabled: false
    tomcat: # 设置默认的隔离级别为读写提交
      default-transaction-isolation: 2
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure # 去除druid配置
  mvc:
    path match:
      matching-strategy: ant_path_matcher

logging:
  config: classpath:logback.xml
  file:
    name: logs/game.log

swagger-ui:
  host: @application.swagger.host@

recruit:
  filter:
    session:
      model: @session.model@
    excludeUrl: /,/health,/static/**,/**/*.html, /**/*.css,/**/*.js,/swagger-resources/**,/swagger-resources,/webjars/**,/v2/api-docs


mybatis:
  mapper-locations: classpath*:com.soft.game.generate.mapper.*.xml
  type-aliases-package: com.soft.game.generate.model
mapper:
  mappers: com.soft.game.generate.BaseMapper
  not-empty: false
  identity: MYSQL






